name: lelamonline_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.2
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12
  http: ^1.5.0
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  provider: ^6.1.5+1
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2

  country_code_picker: ^3.4.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.2
  flutter_html: ^3.0.0
  hive: ^2.2.3
  flutter_hooks: ^0.21.3+1
  dio: ^5.9.0
  hive_flutter: ^1.1.0
  retry: ^3.1.2
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1
  logger: ^2.6.1
  rate_limiter: ^1.0.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/lelam_logo.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/icons/

